### ISSUE TITLE
Task hangs to password forever when executing "SSH into Web App" from a linux app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1683]
**OS:** Mac
**Build Version:** 20200708.1

**Repro Step:**

1. F1 --> Azure App Service: SSH into Web App --> Select a Node/Python runtime linux app.
2. Check the result.

**Expect:**
Execute command "SSH into Web App" successfully.

**Actual:**
Task hangs to password forever when executing "SSH into Web App" from the linux app.
![Screen Shot 2020-07-08 at 4 04 36 PM](https://user-images.githubusercontent.com/62053665/86895120-9925af80-c136-11ea-8aa2-7efab308ee04.png)

**More info:**

1. This issue does not reproduce on Windows/Linux.
2. There is an error when select a NET runtime linux app on Mac/Win10.
 ![Screen Shot 2020-07-08 at 4 55 23 PM](https://user-images.githubusercontent.com/62053665/86899293-6979a600-c13c-11ea-8410-03fec69d21bb.png)

**Comment by nturinski** [comment]
Seems like a timing issue.  I can see that the password was echoed (Docker!) but the console wasn't ready for a password.  This shouldn't be consistent, but can probably be fixed by this: https://github.com/microsoft/vscode-azureappservice/issues/932

**Comment by EricJizbaMSFT** [comment]
Closing in favor of #932

**Comment by v-mengwe** [comment]
Verified this issue on the build 20220222.11, it still reproduces on M1 Air.
<img width="821" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/62053665/155484902-23abd094-3048-48a3-a136-2fe2b5b7a1f0.png">

**Comment by v-mengwe** [comment]
verified on the latest build 20220321.4, this issue doesn't reproduce for now, so close it.
