### ISSUE TITLE
There is no response after executing the action "Reveal in Azure Database extension" for a connected database

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2229]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Service Extension Build Version:** 20220421.6 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps**

1. Expand a Linux Node web app -> "Deployments" node -> Click "Connect to a GitHub Repository..." to connect a repository.
2. Expand the Linux Node web app -> Databases node -> Add a connection and select a Mongo Account.
3. Right click the connected database -> Reveal in Azure Database extension.
4. Check whether succeeds to execute action "Reveal in Azure Database extension" or not.

**Expect:**
Succeed to execute action "Reveal in Azure Database extension".

**Actual:**
There is no response after executing the action "Reveal in Azure Database extension".

**More Info:**
This issue doesn't reproduce without the step 1.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-cosmosdb/pull/2004

**Comment by v-mengwe** [comment]
Verified on the latest build 20220525.1, this issue still reproduces after executing "Focus this Group" for App Services group.

**Repro Steps:**

1. Click "Focus this Group" for App Services group.
2. Expand a Linux Node web app -> Databases node -> Right click the connected MongoDB account -> Reveal in Azure Database extension.

**Actual:**
There is no focus to the connected database after executing the action "Reveal in Azure Database extension".

Is it by design?
