### ISSUE TITLE
There is no step "Choose organization" when changing deployment source to "GitHub"

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2545]
**OS:** Win10
**Build Version:** 20230717.1
**Regression:** Preview Release

**Repro Steps:**

1. Right click a web app -> Click "Configure Deployment Source..." -> Click "GitHub".
2. Check whether the next step is "Choose organization".

**Expect:**
The next step is "Choose organization".
![image](https://github.com/microsoft/vscode-azureappservice/assets/107091828/ba01c4d1-0712-49ec-9067-e196e288e270)

**Actual:**
Pop up a notification of successful update to "GitHub", but doesn't allow to choose organization.

**More Info:**

1. The "GitHub" label doesn't appear next to "Deployments" node after changing deployment source to "GitHub".
2. The "Current source" is "None" when executing "Configure Deployment Source..." command again.
![image](https://github.com/microsoft/vscode-azureappservice/assets/107091828/dfe7a8c1-0750-4b49-922c-26a701c34f10)

**Comment by alexweininger** [comment]
Fixed by #2540

**Comment by v-chenzha** [comment]
Verified this issue on the latest main branch build 20230719.1, it still reproduces now. So, reopen it.

**Comment by v-ruizh** [comment]
This issue has been fixed on the latest build 20230719.13.
